name: Build Flet APK
on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: 'stable'

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          pip install flet requests

      - name: Build APK
        run: flet build apk --package-name com.flet.my_vtk_app --python-version 3.11 --verbose

      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: my-app-release
          path: build/apk/*.apk
